version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi-2
    ports:
      - "8001:8001"
    environment:
      MYAPI1_URL: ${MYAPI1_URL}
    volumes:
      - ${PWD}:/opt/app
